export enum ROUTE {
    LOGIN = "/auth/login",
    SIGNUP = "/auth/signup",
    SIGNUP_SEND_OTP = "/auth/signup/send-otp",
    SIGNUP_VERIFY_OTP = "/auth/signup/verify-otp",
    FORGOT_PASSWORD = "/auth/forgot-password",
    RESET_PASSWORD = "/auth/reset-password",
    LANDING = "/app",
    PLAYGROUND = "/playground",
    DASHBOARD = "/dashboard",
    LOGS = "/dashboard/activity",
    USAGE = "/dashboard/usage",
    APIKEY = "/dashboard/apikey",
    SETTINGS = "/dashboard/settings",
    TERMS = "/terms-of-service",
    PRIVACY = "/privacy-policy",
    PRICING = "/pricing",
    CONTACT = "/contact-us",
} 